=== obfusk/rbtlog/schemas/log.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/obfusk/rbtlog/log/schemas/log.json",
  "title": "rbtlog app rebuild log",
  "description": "rbtlog JSON app rebuild log (logs/*.json)",
  "type": "object",
  "properties": {
    "appid": {
      "description": "APK appid",
      "type": "string"
    },
    "tags": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "appid": {
              "description": "APK appid",
              "type": "string"
            },
            "version_code": {
              "description": "APK version code",
              "type": [
                "integer",
                "null"
              ]
            },
            "version_name": {
              "description": "APK version name",
              "type": [
                "string",
                "null"
              ]
            },
            "tag": {
              "description": "git tag",
              "type": "string"
            },
            "commit": {
              "description": "hash of the commit the tag points to",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{40}$"
            },
            "recipe": {
              "type": "object",
              "properties": {
                "repository": {
                  "description": "git repository URL",
                  "type": "string",
                  "pattern": "^https://.*\\.git$"
                },
                "tag": {
                  "description": "git tag",
                  "type": "string"
                },
                "apk_pattern": {
                  "description": "regex to match against the release assets APK file names",
                  "type": "string"
                },
                "apk_url": {
                  "description": "APK download URL",
                  "type": "string",
                  "pattern": "^https://.*\\.apk$"
                },
                "build": {
                  "description": "build recipe (lines of a bash script)",
                  "type": "string"
                },
                "build_home_dir": {
                  "description": "home directory for the build user",
                  "type": "string"
                },
                "build_repo_dir": {
                  "description": "directory the repo is cloned to and the build is run in",
                  "type": "string"
                },
                "build_timeout": {
                  "description": "build timeout in minutes (not required, default: null, older logs don't have this)",
                  "type": "integer"
                },
                "build_user": {
                  "description": "build user name",
                  "type": "string"
                },
                "provisioning": {
                  "type": "object",
                  "properties": {
                    "android_home": {
                      "description": "android SDK directory",
                      "type": "string"
                    },
                    "build_tools": {
                      "description": "optional Android SDK build-tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "cmake": {
                      "description": "optional Android SDK cmake version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "cmdline_tools": {
                      "description": "Android SDK cmdline-tools specification",
                      "type": "object",
                      "properties": {
                        "version": {
                          "description": "Android cmdline-tools version",
                          "type": "string"
                        },
                        "url": {
                          "description": "download URL",
                          "type": "string",
                          "pattern": "^https://.*$"
                        },
                        "sha256": {
                          "description": "SHA-256 checksum (hex)",
                          "type": "string",
                          "pattern": "^[0-9a-f]{64}$"
                        }
                      },
                      "required": [
                        "version",
                        "url",
                        "sha256"
                      ],
                      "additionalProperties": false
                    },
                    "extra_packages": {
                      "description": "extra packages to install",
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "image": {
                      "description": "docker/podman image",
                      "type": "string"
                    },
                    "jdk": {
                      "description": "jdk package",
                      "type": "string"
                    },
                    "ndk": {
                      "description": "optional Android NDK version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "platform": {
                      "description": "optional Android SDK version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "platform_tools": {
                      "description": "optional Android SDK platform-tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "tools": {
                      "description": "optional Android SDK tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "verify_gradle_wrapper": {
                      "description": "whether to verify the gradle-wrapper.jar checksum (not required, older logs don't have this)",
                      "type": "boolean"
                    },
                    "windows_like": {
                      "description": "whether to disable symlinks for git (not required, default: false, older logs don't have this)",
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "android_home",
                    "build_tools",
                    "cmake",
                    "cmdline_tools",
                    "extra_packages",
                    "image",
                    "jdk",
                    "ndk",
                    "platform",
                    "platform_tools",
                    "tools"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "repository",
                "tag",
                "apk_pattern",
                "apk_url",
                "build",
                "build_home_dir",
                "build_repo_dir",
                "build_user",
                "provisioning"
              ],
              "additionalProperties": false
            },
            "timestamp": {
              "description": "build timestamp",
              "type": "integer"
            },
            "reproducible": {
              "description": "reproducibility test result",
              "type": [
                "boolean",
                "null"
              ]
            },
            "error": {
              "description": "error message",
              "type": [
                "string",
                "null"
              ]
            },
            "build_log": {
              "description": "build log",
              "type": "string"
            },
            "upstream_signed_apk_sha256": {
              "description": "SHA-256 checksum (hex) of upsteam APK",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            },
            "built_unsigned_apk_sha256": {
              "description": "SHA-256 checksum (hex) of built unsigned APK",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            },
            "signature_copied_apk_sha256": {
              "description": "SHA-256 checksum (hex) of APK with signature copied",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            }
          },
          "required": [
            "appid",
            "version_code",
            "version_name",
            "tag",
            "commit",
            "recipe",
            "timestamp",
            "reproducible",
            "error",
            "build_log",
            "upstream_signed_apk_sha256",
            "built_unsigned_apk_sha256",
            "signature_copied_apk_sha256"
          ],
          "additionalProperties": false
        }
      }
    },
    "version_codes": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "sha256": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[0-9a-f]{64}$"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "appid",
    "tags",
    "version_codes",
    "sha256"
  ],
  "additionalProperties": false
}

=== obfusk/rbtlog/logs/org.netdex.androidusbscript.json
{
  "appid": "org.netdex.androidusbscript",
  "tags": {
    "1.2.0": [
      {
        "appid": "org.netdex.androidusbscript",
        "version_code": 120,
        "version_name": "1.2.0",
        "tag": "1.2.0",
        "commit": "7b314f90b45610b440cc258fcb2b64a72d0cefeb",
        "recipe": {
          "repository": "https://github.com/Netdex/android-usb-script.git",
          "tag": "1.2.0",
          "apk_pattern": "android-usb-script_.*\\.apk",
          "apk_url": "https://github.com/Netdex/android-usb-script/releases/download/1.2.0/android-usb-script_1.2.0.apk",
          "build": "chmod +x gradlew\n./gradlew assembleRelease\nOUT=app/build/outputs/apk/release/app-release-unsigned.apk\ngit clone -b v0.2.4 https://github.com/obfusk/reproducible-apk-tools.git\nreproducible-apk-tools/inplace-fix.py --internal --zipalign fix-newlines \"$OUT\" 'META-INF/services/*' 'assets/*.lua'\nmv \"$OUT\" /outputs/unsigned.apk\n",
          "build_home_dir": "/build",
          "build_repo_dir": "/build/repo",
          "build_user": "build",
          "provisioning": {
            "android_home": "/opt/sdk",
            "build_tools": null,
            "cmake": null,
            "cmdline_tools": {
              "version": "12.0",
              "url": "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip",
              "sha256": "2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258"
            },
            "extra_packages": [
              "python3"
            ],
            "image": "debian:bookworm-slim",
            "jdk": "openjdk-17-jdk-headless",
            "ndk": null,
            "platform": null,
            "platform_tools": null,
            "tools": null,
            "verify_gradle_wrapper": true
          }
        },
        "timestamp": 1710777695,
        "reproducible": true,
        "error": null,
        "build_log": "RUN COMMAND podman pull -- debian:bookworm-slim\nResolved \"debian\" as an alias (/etc/containers/registries.conf.d/shortnames.conf)\nTrying to pull docker.io/library/debian:bookworm-slim...\nGetting image source signatures\nCopying blob sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345\nCopying blob sha256:8a1e25ce7c4f75e372e9884f8f7b1bedcfe4a7a7d452eb4b0a1c7477c9a90345\nCopying config sha256:dd8416105e9e7aa94aa22d8839c4359a237cbcd30f8b464bd961cbba9fce8a54\nWriting manifest to image destination\nStoring signatures\ndd8416105e9e7aa94aa22d8839c4359a237cbcd30f8b464bd961cbba9fce8a54\nRUN COMMAND podman run --rm --volume /tmp/tmpxrzkn7jr/outputs:/outputs --volume /tmp/tmpxrzkn7jr/scripts:/scripts:ro --env ANDROID_HOME=/opt/sdk --env APP_REPOSITORY=https://github.com/Netdex/android-usb-script.git --env APP_TAG=1.2.0 --env APP_COMMIT=7b314f90b45610b440cc258fcb2b64a72d0cefeb --env BUILD_USER=build --env BUILD_HOME_DIR=/build --env BUILD_REPO_DIR=/build/repo --env PROVISIONING_BUILD_TOOLS= --env PROVISIONING_CMAKE= --env PROVISIONING_CMDLINE_TOOLS_VERSION=12.0 --env PROVISIONING_CMDLINE_TOOLS_URL=https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip --env PROVISIONING_CMDLINE_TOOLS_SHA256=2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258 --env PROVISIONING_EXTRA_PACKAGES=python3 --env PROVISIONING_JDK=openjdk-17-jdk-headless --env PROVISIONING_NDK= --env PROVISIONING_PLATFORM= --env PROVISIONING_PLATFORM_TOOLS= --env PROVISIONING_TOOLS= --env VERIFY_GRADLE_WRAPPER=yes -- debian:bookworm-slim bash -c timeout 10m /scripts/provision-root.sh && cd /build && timeout 10m su build /scripts/provision.sh && cd /build/repo && timeout 20m su build /scripts/build.sh\n+ export DEBIAN_FRONTEND=noninteractive\n+ DEBIAN_FRONTEND=noninteractive\n+ apt-get update\nGet:1 http://deb.debian.org/debian bookworm InRelease [151 kB]\nGet:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]\nGet:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]\nGet:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]\nGet:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]\nGet:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [146 kB]\nFetched 9200 kB in 1s (10.6 MB/s)\nReading package lists...\n+ apt-get upgrade -y\nReading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n+ readarray -d , -t extra_packages\n++ printf %s python3\n+ apt-get install --no-install-recommends -y git wget unzip openjdk-17-jdk-headless python3\nReading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  ca-certificates ca-certificates-java fontconfig-config fonts-dejavu-core\n  git-man java-common libasound2 libasound2-data libavahi-client3\n  libavahi-common-data libavahi-common3 libbrotli1 libcups2 libcurl3-gnutls\n  libdbus-1-3 liberror-perl libexpat1 libfontconfig1 libfreetype6\n  libgdbm-compat4 libgdbm6 libglib2.0-0 libgraphite2-3 libgssapi-krb5-2\n  libharfbuzz0b libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3\n  libkrb5support0 liblcms2-2 libldap-2.5-0 libncursesw6 libnghttp2-14 libnsl2\n  libnspr4 libnss3 libpcsclite1 libperl5.36 libpng16-16 libpsl5\n  libpython3-stdlib libpython3.11-minimal libpython3.11-stdlib libreadline8\n  librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0 libssh2-1 libssl3\n  libtirpc-common libtirpc3 media-types openjdk-17-jre-headless openssl perl\n  perl-modules-5.36 python3-minimal python3.11 python3.11-minimal\n  readline-common\nSuggested packages:\n  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-email git-gui\n  gitk gitweb git-cvs git-mediawiki git-svn default-jre libasound2-plugins\n  alsa-utils cups-common gdbm-l10n low-memory-monitor krb5-doc krb5-user\n  liblcms2-utils pcscd sensible-utils openjdk-17-demo openjdk-17-source\n  libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho\n  fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic perl-doc\n  libterm-readline-gnu-perl | libterm-readline-perl-perl make\n  libtap-harness-archive-perl python3-doc python3-tk python3-venv\n  python3.11-venv python3.11-doc binutils binfmt-support readline-doc zip\nRecommended packages:\n  patch less ssh-client alsa-ucm-conf alsa-topology-conf dbus libglib2.0-data\n  shared-mime-info xdg-user-dirs krb5-locales libldap-common libgpm2\n  publicsuffix libsasl2-modules netbase\nThe following NEW packages will be installed:\n  ca-certificates ca-certificates-java fontconfig-config fonts-dejavu-core git\n  git-man java-common libasound2 libasound2-data libavahi-client3\n  libavahi-common-data libavahi-common3 libbrotli1 libcups2 libcurl3-gnutls\n  libdbus-1-3 liberror-perl libexpat1 libfontconfig1 libfreetype6\n  libgdbm-compat4 libgdbm6 libglib2.0-0 libgraphite2-3 libgssapi-krb5-2\n  libharfbuzz0b libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3\n  libkrb5support0 liblcms2-2 libldap-2.5-0 libncursesw6 libnghttp2-14 libnsl2\n  libnspr4 libnss3 libpcsclite1 libperl5.36 libpng16-16 libpsl5\n  libpython3-stdlib libpython3.11-minimal libpython3.11-stdlib libreadline8\n  librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0 libssh2-1 libssl3\n  libtirpc-common libtirpc3 media-types openjdk-17-jdk-headless\n  openjdk-17-jre-headless openssl perl perl-modules-5.36 python3\n  python3-minimal python3.11 python3.11-minimal readline-common unzip wget\n0 upgraded, 67 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 154 MB of archives.\nAfter this operation, 433 MB of additional disk space will be used.\nGet:1 http://deb.debian.org/debian bookworm/main amd64 perl-modules-5.36 all 5.36.0-7+deb12u1 [2815 kB]\nGet:2 http://deb.debian.org/debian bookworm/main amd64 libgdbm6 amd64 1.23-3 [72.2 kB]\nGet:3 http://deb.debian.org/debian bookworm/main amd64 libgdbm-compat4 amd64 1.23-3 [48.2 kB]\nGet:4 http://deb.debian.org/debian bookworm/main amd64 libperl5.36 amd64 5.36.0-7+deb12u1 [4218 kB]\nGet:5 http://deb.debian.org/debian bookworm/main amd64 perl amd64 5.36.0-7+deb12u1 [239 kB]\nGet:6 http://deb.debian.org/debian bookworm/main amd64 libssl3 amd64 3.0.11-1~deb12u2 [2019 kB]\nGet:7 http://deb.debian.org/debian bookworm/main amd64 libpython3.11-minimal amd64 3.11.2-6 [813 kB]\nGet:8 http://deb.debian.org/debian bookworm/main amd64 libexpat1 amd64 2.5.0-1 [99.3 kB]\nGet:9 http://deb.debian.org/debian bookworm/main amd64 python3.11-minimal amd64 3.11.2-6 [2064 kB]\nGet:10 http://deb.debian.org/debian bookworm/main amd64 python3-minimal amd64 3.11.2-1+b1 [26.3 kB]\nGet:11 http://deb.debian.org/debian bookworm/main amd64 media-types all 10.0.0 [26.1 kB]\nGet:12 http://deb.debian.org/debian bookworm/main amd64 libncursesw6 amd64 6.4-4 [134 kB]\nGet:13 http://deb.debian.org/debian bookworm/main amd64 libkrb5support0 amd64 1.20.1-2+deb12u1 [32.4 kB]\nGet:14 http://deb.debian.org/debian bookworm/main amd64 libk5crypto3 amd64 1.20.1-2+deb12u1 [78.9 kB]\nGet:15 http://deb.debian.org/debian bookworm/main amd64 libkeyutils1 amd64 1.6.3-2 [8808 B]\nGet:16 http://deb.debian.org/debian bookworm/main amd64 libkrb5-3 amd64 1.20.1-2+deb12u1 [332 kB]\nGet:17 http://deb.debian.org/debian bookworm/main amd64 libgssapi-krb5-2 amd64 1.20.1-2+deb12u1 [134 kB]\nGet:18 http://deb.debian.org/debian bookworm/main amd64 libtirpc-common all 1.3.3+ds-1 [14.0 kB]\nGet:19 http://deb.debian.org/debian bookworm/main amd64 libtirpc3 amd64 1.3.3+ds-1 [85.2 kB]\nGet:20 http://deb.debian.org/debian bookworm/main amd64 libnsl2 amd64 1.3.0-2 [39.5 kB]\nGet:21 http://deb.debian.org/debian bookworm/main amd64 readline-common all 8.2-1.3 [69.0 kB]\nGet:22 http://deb.debian.org/debian bookworm/main amd64 libreadline8 amd64 8.2-1.3 [166 kB]\nGet:23 http://deb.debian.org/debian bookworm/main amd64 libsqlite3-0 amd64 3.40.1-2 [837 kB]\nGet:24 http://deb.debian.org/debian bookworm/main amd64 libpython3.11-stdlib amd64 3.11.2-6 [1796 kB]\nG
